// Code generated by protoc-gen-go-gclient. DO NOT EDIT.
// versions:
// - protoc-gen-go-gclient v1.3.0
// - protoc             v3.12.4
// source: service/admin/admin.proto

package admin_grpc

import (
	context "context"
	fmt "fmt"
	gira "github.com/lujingwei002/gira"
	facade "github.com/lujingwei002/gira/facade"
	options "github.com/lujingwei002/gira/registry/service/options"
	grpc "google.golang.org/grpc"
	sync "sync"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

type ReloadResourceResponse_MulticastResult struct {
	PeerCount int
	Errors    []error
	Responses []*ReloadResourceResponse
}

func (r *ReloadResourceResponse_MulticastResult) Error() error {
	if len(r.Errors) <= 0 {
		return nil
	}
	return r.Errors[0]
}

type ReloadResourceResponse1_MulticastResult struct {
	PeerCount int
	Errors    []error
	Responses []*ReloadResourceResponse1
}

func (r *ReloadResourceResponse1_MulticastResult) Error() error {
	if len(r.Errors) <= 0 {
		return nil
	}
	return r.Errors[0]
}

type ReloadResourceResponse2_MulticastResult struct {
	PeerCount int
	Errors    []error
	Responses []*ReloadResourceResponse2
}

func (r *ReloadResourceResponse2_MulticastResult) Error() error {
	if len(r.Errors) <= 0 {
		return nil
	}
	return r.Errors[0]
}

const (
	AdminServiceName = "admin_grpc.Admin"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClients interface {
	WithServiceName(serviceName string) AdminClients
	WithUnicast() AdminClientsUnicast
	WithMulticast(count int) AdminClientsMulticast
	WithBroadcast() AdminClientsMulticast

	ReloadResource(ctx context.Context, address string, in *ReloadResourceRequest, opts ...grpc.CallOption) (*ReloadResourceResponse, error)
	ReloadResource1(ctx context.Context, address string, opts ...grpc.CallOption) (Admin_ReloadResource1Client, error)
	ReloadResource2(ctx context.Context, address string, in *ReloadResourceRequest2, opts ...grpc.CallOption) (Admin_ReloadResource2Client, error)
	ReloadResource3(ctx context.Context, address string, opts ...grpc.CallOption) (Admin_ReloadResource3Client, error)
}

type AdminClientsMulticast interface {
	WithRegex(regex string) AdminClientsMulticast
	ReloadResource(ctx context.Context, in *ReloadResourceRequest, opts ...grpc.CallOption) *ReloadResourceResponse_MulticastResult
	ReloadResource1(ctx context.Context, opts ...grpc.CallOption) *Admin_ReloadResource1Client_MulticastResult
	ReloadResource2(ctx context.Context, in *ReloadResourceRequest2, opts ...grpc.CallOption) *Admin_ReloadResource2Client_MulticastResult
	ReloadResource3(ctx context.Context, opts ...grpc.CallOption) *Admin_ReloadResource3Client_MulticastResult
}

type AdminClientsUnicast interface {
	WithServiceName(serviceName string) AdminClientsUnicast
	WithPeer(peer *gira.Peer) AdminClientsUnicast
	WithAddress(address string) AdminClientsUnicast

	ReloadResource(ctx context.Context, in *ReloadResourceRequest, opts ...grpc.CallOption) (*ReloadResourceResponse, error)
	ReloadResource1(ctx context.Context, opts ...grpc.CallOption) (Admin_ReloadResource1Client, error)
	ReloadResource2(ctx context.Context, in *ReloadResourceRequest2, opts ...grpc.CallOption) (Admin_ReloadResource2Client, error)
	ReloadResource3(ctx context.Context, opts ...grpc.CallOption) (Admin_ReloadResource3Client, error)
}

type adminClients struct {
	mu          sync.Mutex
	clientPool  map[string]*sync.Pool
	serviceName string
}

func NewAdminClients() AdminClients {
	return &adminClients{
		serviceName: AdminServiceName,
		clientPool:  make(map[string]*sync.Pool, 0),
	}
}

var DefaultAdminClients = NewAdminClients()

func (c *adminClients) getClient(address string) (AdminClient, error) {
	c.mu.Lock()
	var pool *sync.Pool
	var ok bool
	if pool, ok = c.clientPool[address]; !ok {
		pool = &sync.Pool{
			New: func() any {
				conn, err := grpc.Dial(address, grpc.WithInsecure())
				if err != nil {
					return err
				}
				client := NewAdminClient(conn)
				return client
			},
		}
		c.clientPool[address] = pool
		c.mu.Unlock()
	} else {
		c.mu.Unlock()
	}
	if v := pool.Get(); v == nil {
		return nil, gira.ErrGrpcClientPoolNil
	} else if err, ok := v.(error); ok {
		return nil, err
	} else {
		return v.(AdminClient), nil
	}
}

func (c *adminClients) putClient(address string, client AdminClient) {
	c.mu.Lock()
	var pool *sync.Pool
	var ok bool
	if pool, ok = c.clientPool[address]; ok {
		pool.Put(client)
	}
	c.mu.Unlock()
}

func (c *adminClients) WithServiceName(serviceName string) AdminClients {
	c.serviceName = serviceName
	return c
}

func (c *adminClients) WithUnicast() AdminClientsUnicast {
	u := &adminClientsUnicast{
		client: c,
	}
	return u
}

func (c *adminClients) WithMulticast(count int) AdminClientsMulticast {
	u := &adminClientsMulticast{
		count:       count,
		serviceName: fmt.Sprintf("%s/", c.serviceName),
		client:      c,
	}
	return u
}

func (c *adminClients) WithBroadcast() AdminClientsMulticast {
	u := &adminClientsMulticast{
		count:       -1,
		serviceName: fmt.Sprintf("%s/", c.serviceName),
		client:      c,
	}
	return u
}

func (c *adminClients) ReloadResource(ctx context.Context, address string, in *ReloadResourceRequest, opts ...grpc.CallOption) (*ReloadResourceResponse, error) {
	client, err := c.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.putClient(address, client)
	out, err := client.ReloadResource(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClients) ReloadResource1(ctx context.Context, address string, opts ...grpc.CallOption) (Admin_ReloadResource1Client, error) {
	client, err := c.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.putClient(address, client)
	out, err := client.ReloadResource1(ctx, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClients) ReloadResource2(ctx context.Context, address string, in *ReloadResourceRequest2, opts ...grpc.CallOption) (Admin_ReloadResource2Client, error) {
	client, err := c.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.putClient(address, client)
	out, err := client.ReloadResource2(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClients) ReloadResource3(ctx context.Context, address string, opts ...grpc.CallOption) (Admin_ReloadResource3Client, error) {
	client, err := c.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.putClient(address, client)
	out, err := client.ReloadResource3(ctx, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type adminClientsUnicast struct {
	peer        *gira.Peer
	serviceName string
	address     string
	client      *adminClients
}

func (c *adminClientsUnicast) WithServiceName(serviceName string) AdminClientsUnicast {
	u := &adminClientsUnicast{
		client:      c.client,
		serviceName: fmt.Sprintf("%s/%s", c.client.serviceName, serviceName),
	}
	return u
}

func (c *adminClientsUnicast) WithPeer(peer *gira.Peer) AdminClientsUnicast {
	u := &adminClientsUnicast{
		client: c.client,
		peer:   peer,
	}
	return u
}

func (c *adminClientsUnicast) WithAddress(address string) AdminClientsUnicast {
	u := &adminClientsUnicast{
		client:  c.client,
		address: address,
	}
	return u
}

func (c *adminClientsUnicast) ReloadResource(ctx context.Context, in *ReloadResourceRequest, opts ...grpc.CallOption) (*ReloadResourceResponse, error) {
	var address string
	if len(c.address) > 0 {
		address = c.address
	} else if c.peer != nil {
		address = c.peer.GrpcAddr
	} else if len(c.serviceName) > 0 {
		if peers, err := facade.WhereIsService(c.serviceName); err != nil {
			return nil, err
		} else if len(peers) < 1 {
			return nil, gira.ErrPeerNotFound.Trace()
		} else {
			address = peers[0].GrpcAddr
		}
	}
	if len(address) <= 0 {
		return nil, gira.ErrInvalidArgs.Trace()
	}
	client, err := c.client.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.client.putClient(address, client)
	out, err := client.ReloadResource(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClientsUnicast) ReloadResource1(ctx context.Context, opts ...grpc.CallOption) (Admin_ReloadResource1Client, error) {
	var address string
	if len(c.address) > 0 {
		address = c.address
	} else if c.peer != nil {
		address = c.peer.GrpcAddr
	} else if len(c.serviceName) > 0 {
		if peers, err := facade.WhereIsService(c.serviceName); err != nil {
			return nil, err
		} else if len(peers) < 1 {
			return nil, gira.ErrPeerNotFound.Trace()
		} else {
			address = peers[0].GrpcAddr
		}
	}
	if len(address) <= 0 {
		return nil, gira.ErrInvalidArgs.Trace()
	}
	client, err := c.client.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.client.putClient(address, client)
	out, err := client.ReloadResource1(ctx, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClientsUnicast) ReloadResource2(ctx context.Context, in *ReloadResourceRequest2, opts ...grpc.CallOption) (Admin_ReloadResource2Client, error) {
	var address string
	if len(c.address) > 0 {
		address = c.address
	} else if c.peer != nil {
		address = c.peer.GrpcAddr
	} else if len(c.serviceName) > 0 {
		if peers, err := facade.WhereIsService(c.serviceName); err != nil {
			return nil, err
		} else if len(peers) < 1 {
			return nil, gira.ErrPeerNotFound.Trace()
		} else {
			address = peers[0].GrpcAddr
		}
	}
	if len(address) <= 0 {
		return nil, gira.ErrInvalidArgs.Trace()
	}
	client, err := c.client.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.client.putClient(address, client)
	out, err := client.ReloadResource2(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClientsUnicast) ReloadResource3(ctx context.Context, opts ...grpc.CallOption) (Admin_ReloadResource3Client, error) {
	var address string
	if len(c.address) > 0 {
		address = c.address
	} else if c.peer != nil {
		address = c.peer.GrpcAddr
	} else if len(c.serviceName) > 0 {
		if peers, err := facade.WhereIsService(c.serviceName); err != nil {
			return nil, err
		} else if len(peers) < 1 {
			return nil, gira.ErrPeerNotFound.Trace()
		} else {
			address = peers[0].GrpcAddr
		}
	}
	if len(address) <= 0 {
		return nil, gira.ErrInvalidArgs.Trace()
	}
	client, err := c.client.getClient(address)
	if err != nil {
		return nil, err
	}
	defer c.client.putClient(address, client)
	out, err := client.ReloadResource3(ctx, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type adminClientsMulticast struct {
	// 不变
	count       int
	serviceName string
	// 可变
	regex  string
	client *adminClients
}

type Admin_ReloadResource1Client_MulticastResult struct {
	PeerCount int
	Errors    []error
	Responses []Admin_ReloadResource1Client
}

func (r *Admin_ReloadResource1Client_MulticastResult) Error() error {
	if len(r.Errors) <= 0 {
		return nil
	}
	return r.Errors[0]
}

type Admin_ReloadResource2Client_MulticastResult struct {
	PeerCount int
	Errors    []error
	Responses []Admin_ReloadResource2Client
}

func (r *Admin_ReloadResource2Client_MulticastResult) Error() error {
	if len(r.Errors) <= 0 {
		return nil
	}
	return r.Errors[0]
}

type Admin_ReloadResource3Client_MulticastResult struct {
	PeerCount int
	Errors    []error
	Responses []Admin_ReloadResource3Client
}

func (r *Admin_ReloadResource3Client_MulticastResult) Error() error {
	if len(r.Errors) <= 0 {
		return nil
	}
	return r.Errors[0]
}
func (c *adminClientsMulticast) WithRegex(regex string) AdminClientsMulticast {
	u := &adminClientsMulticast{
		client: c.client,
		count:  c.count,
		regex:  regex,
	}
	return u
}

func (c *adminClientsMulticast) ReloadResource(ctx context.Context, in *ReloadResourceRequest, opts ...grpc.CallOption) *ReloadResourceResponse_MulticastResult {
	var peers []*gira.Peer
	var whereOpts []options.WhereOption
	// 多播
	if c.count > 0 {
		whereOpts = append(whereOpts, options.WithWhereMaxCountOption(c.count))
	}
	if len(c.regex) > 0 {
		whereOpts = append(whereOpts, options.WithWhereRegexOption(c.regex))
	}
	result := &ReloadResourceResponse_MulticastResult{}
	peers, err := facade.WhereIsService(c.serviceName, whereOpts...)
	if err != nil {
		result.Errors = append(result.Errors, err)
		return result
	}
	result.PeerCount = len(peers)
	for _, peer := range peers {
		client, err := c.client.getClient(peer.GrpcAddr)
		if err != nil {
			result.Errors = append(result.Errors, err)
			continue
		}
		out, err := client.ReloadResource(ctx, in, opts...)
		if err != nil {
			result.Errors = append(result.Errors, err)
			c.client.putClient(peer.GrpcAddr, client)
			continue
		}
		c.client.putClient(peer.GrpcAddr, client)
		result.Responses = append(result.Responses, out)
	}
	return result
}

func (c *adminClientsMulticast) ReloadResource1(ctx context.Context, opts ...grpc.CallOption) *Admin_ReloadResource1Client_MulticastResult {
	var peers []*gira.Peer
	var whereOpts []options.WhereOption
	// 多播
	if c.count > 0 {
		whereOpts = append(whereOpts, options.WithWhereMaxCountOption(c.count))
	}
	if len(c.regex) > 0 {
		whereOpts = append(whereOpts, options.WithWhereRegexOption(c.regex))
	}
	result := &Admin_ReloadResource1Client_MulticastResult{}
	peers, err := facade.WhereIsService(c.serviceName, whereOpts...)
	if err != nil {
		result.Errors = append(result.Errors, err)
		return result
	}
	result.PeerCount = len(peers)
	for _, peer := range peers {
		client, err := c.client.getClient(peer.GrpcAddr)
		if err != nil {
			result.Errors = append(result.Errors, err)
			continue
		}
		out, err := client.ReloadResource1(ctx, opts...)
		if err != nil {
			result.Errors = append(result.Errors, err)
			c.client.putClient(peer.GrpcAddr, client)
			continue
		}
		result.Responses = append(result.Responses, out)
	}
	return result
}

func (c *adminClientsMulticast) ReloadResource2(ctx context.Context, in *ReloadResourceRequest2, opts ...grpc.CallOption) *Admin_ReloadResource2Client_MulticastResult {
	var peers []*gira.Peer
	var whereOpts []options.WhereOption
	// 多播
	if c.count > 0 {
		whereOpts = append(whereOpts, options.WithWhereMaxCountOption(c.count))
	}
	if len(c.regex) > 0 {
		whereOpts = append(whereOpts, options.WithWhereRegexOption(c.regex))
	}
	result := &Admin_ReloadResource2Client_MulticastResult{}
	peers, err := facade.WhereIsService(c.serviceName, whereOpts...)
	if err != nil {
		result.Errors = append(result.Errors, err)
		return result
	}
	result.PeerCount = len(peers)
	for _, peer := range peers {
		client, err := c.client.getClient(peer.GrpcAddr)
		if err != nil {
			result.Errors = append(result.Errors, err)
			continue
		}
		out, err := client.ReloadResource2(ctx, in, opts...)
		if err != nil {
			result.Errors = append(result.Errors, err)
			c.client.putClient(peer.GrpcAddr, client)
			continue
		}
		result.Responses = append(result.Responses, out)
	}
	return result
}

func (c *adminClientsMulticast) ReloadResource3(ctx context.Context, opts ...grpc.CallOption) *Admin_ReloadResource3Client_MulticastResult {
	var peers []*gira.Peer
	var whereOpts []options.WhereOption
	// 多播
	if c.count > 0 {
		whereOpts = append(whereOpts, options.WithWhereMaxCountOption(c.count))
	}
	if len(c.regex) > 0 {
		whereOpts = append(whereOpts, options.WithWhereRegexOption(c.regex))
	}
	result := &Admin_ReloadResource3Client_MulticastResult{}
	peers, err := facade.WhereIsService(c.serviceName, whereOpts...)
	if err != nil {
		result.Errors = append(result.Errors, err)
		return result
	}
	result.PeerCount = len(peers)
	for _, peer := range peers {
		client, err := c.client.getClient(peer.GrpcAddr)
		if err != nil {
			result.Errors = append(result.Errors, err)
			continue
		}
		out, err := client.ReloadResource3(ctx, opts...)
		if err != nil {
			result.Errors = append(result.Errors, err)
			c.client.putClient(peer.GrpcAddr, client)
			continue
		}
		result.Responses = append(result.Responses, out)
	}
	return result
}
